#!/bin/bash
#
# Project spectral lines over continuum or other 2-D maps and visualize using
# like e.g. Google Maps.
#
# Created by: Fernando Olguin
#

##### Environment #####
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

##### Functions #####
function usage () {
echo "usage:"
}

function base_layer () {
    local script="${DIR}/baselayer.py"
    python $script $* &
    local pid="$!"
    if [[ $verbose -eq 1 ]]
    then
        echo "Base layer plot PID: $pid"
    fi
}

function overlay () {
    local script="${DIR}/overlay.py"
    python $script $* &
    local pid="$!"
    if [[ $verbose -eq 1 ]]
    then
        echo "Overlay plot PID: $!"
    fi
}

function get_tiles () {
    local flags="-density $1 -antialias -resize ${2}x${2} $3"
    flags="$flags -crop 256x256 +adjoin -extent 256x256"
    if [[ $6 != "" ]]
    then
        echo "Setting transparent: $6"
        flags="$flags -transparent $6"
    fi
    flags="$flags -set filename:tile"
    convert $flags \
        "%[fx:floor(page.x/256)]_%[fx:floor(page.y/256)]" \
        +repage "tiles/${4}_${5}_%[filename:tile].png" &
    echo "$4 level $5 PID: $!"
}

function base_layer_pipe () {
    # Plots
    if [[ ! -e "baselayer.pdf" ]] || [[ $redo == 1 ]]
    then
        echo "Ploting base layer"
        base_layer "--blc $blc --trc $trc $baselayers baselayer.pdf"
        wait
    else
        echo "Base layer already plotted"
    fi

    # Create tiles
    for z in $(seq 0 $zoom)
    do
        local maxtile=$(echo "2^$z - 1" | bc)
        local lasttile="tiles/baselayer_${z}_${maxtile}_${maxtile}.png"
        if [[ $redo == 1 ]] || [[ ! -e $lasttile ]]
        then
            local zlevel=$((maxtile + 1))
            zlevel=$((zlevel * 256))
            get_tiles "300" "$zlevel" "baselayer.pdf" "baselayer" "$z"
        else
            echo "Tiles for base layer level $z already done"
        fi
    done
    wait
    echo "Base layer finished"
}

function overlay_pipe () {
    # Plots
    if [[ ! -e "overlay.pdf" ]] || [[ $redo == 1 ]]
    then
        echo "Ploting overlay layer"
        overlay "--blc $blc --trc $trc -c $ch $overlays overlay.pdf"
        wait
    else
        echo "Overlay layer already plotted"
    fi

    # Create tiles
    for z in $(seq 4 $zoom)
    do
        local maxtile=$(echo "2^$z - 1" | bc)
        local lasttile="tiles/overlay_${z}_${maxtile}_${maxtile}.png"
        if [[ $redo == 1 ]] || [[ ! -e $lasttile ]]
        then
            local zlevel=$((maxtile + 1))
            zlevel=$((zlevel * 256))
            get_tiles "600" "$zlevel" "overlay.pdf" "overlay" "$z" "white"
        else
            echo "Tiles for overlay level $z already done"
        fi
    done
    wait
    echo "Overlay layer finished"
}

##### Main #####
echo "Starting time: $(date)"
baselayers=""
ovelays=""
redo=1
verbose=0
zoom=6
while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        -v | --verbose )        verbose=1
                                shift
                                ;;
        -n | --noredo )         redo=0
                                shift
                                ;;
        -c | --chanrange )      shift
                                ch="$1 $2"
                                shift 2
                                ;;
        --trc )                 shift
                                trc="$1 $2"
                                shift 2
                                ;;
        --blc )                 shift
                                blc="$1 $2"
                                shift 2
                                ;;
        -z | --zoom )           shift
                                zoom=$1
                                shift
                                ;;
        * )                     overlays=$1
                                shift
                                baselayers=$1
                                shift
                                break
                                ;;
    esac
done

if [[ ! -d "tiles" ]]
then
    echo "Creating directory tiles"
    mkdir "tiles"
fi

base_layer_pipe &
overlay_pipe &
wait
cp ${DIR}/index.html .
firefox index.html
echo "Finish time: $(date)"

