#!/bin/bash
#
# Project spectral lines over continuum or other 2-D maps and visualize using
# like e.g. Google Maps.
#
# Created by: Fernando Olguin
#

##### Environment #####
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

##### Functions #####
function usage () {
echo "usage:"
}

function base_layer () {
    local script="${DIR}/baselayer.py"
    python $script $* 
    #echo "Base layer plot PID: $!"
}

function overlay () {
    local script="${DIR}/overlay.py"
    python $script $*
    #echo "Overlay plot PID: $!"
}

function get_tiles () {
    if [ ! -d "tiles" ]
    then
        echo "Creating directory tiles"
        mkdir "tiles"
    fi
    local flags="-density $1 -antialias -resize ${2}x${2} $3"
    flags="$flags -crop 256x256 +adjoin -extent 256x256 -transparent white"
    flags="$flags -set filename:tile"
    flags="$flags \"%[fx:floor(page.x/256)]_%[fx:floor(page.y/256)]\""
    flags="$flags +repage \"tiles/${4}_${5}_%[filename:tile].png\""
    convert $flags &
    echo "$4 level $5 PID: $!"
}

##### Main #####
baselayers=""
ovelays=""
while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        -c | --chanrange )      shift
                                ch1=$1
                                shift
                                ch2=$1
                                shift
                                ;;
        --trc )                 shift
                                trc1=$1
                                shift
                                trc2=$1
                                shift
                                ;;
        --blc )                 shift
                                blc1=$1
                                shift
                                blc2=$1
                                shift
                                ;;
        * )                     overlays=$1
                                shift
                                baselayers=$1
                                shift
                                break
                                ;;
    esac
done

#base_layer "--blc $blc1 $blc2 --trc $trc1 $trc2 $baselayers baselayer.pdf"

overlay "--blc $blc1 $blc2 --trc $trc1 $trc2 -c $ch1 $ch2 $overlays overlay.pdf"
wait
